gwhs/2025-Reefscape

src/main/java/frc/robot/RobotContainer.java, vendordeps/DogLog.json
In this task, I imported doglog into the 2025 vscode for this season.
=> did doglog assignment

Advantage Scope Custom Assets/Robot_5507-Kitbot/config.json
To play around with camera location to see what the cameras see
https://3.basecamp.com/5677500/buckets/34348388/messages/8189065635
=> Added custom kitbot asset

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/Telemetry.java
- Logged command scheduler to smart dashboard
- pathplanner warmup command
- clean up
=> Logged command scheduler to smart dashboard + pathplanner warmup command + msc

build.gradle
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8204391287
=> set up profiling

src/main/java/frc/robot/Robot.java
=> I did log robot assignment

.vscode/settings.json, src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/led/LedSubsystem.java, src/main/java/frc/robot/subsystems/led/LedUtils.java
I added LED support, the length is assumed to be 60 but can be changed if needed
=> LED Subsystem :)

src/main/java/frc/robot/RobotContainer.java
Changed weird velocity for path planner
=> Add back pathplanner warm up command

src/main/java/frc/robot/EagleUtil.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/DriveCommand.java, src/main/java/frc/robot/subsystems/arm/ArmConstants.java, src/main/java/frc/robot/subsystems/arm/ArmIOReal.java, src/main/java/frc/robot/subsystems/arm/ArmSubsystem.java, src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOReal.java, src/main/java/frc/robot/subsystems/elevator/ElevatorSubsystem.java
- changed reef setpoint offsets,
-  binding things onto buttons: x = face coral station and intake pos, release x = coral handoff,
- when no buttons are pressed, robot will now auto face reef. 
- right trigger = prep score + robot centric + slow, 
- release right trigger = stow pos
- driver can override with rotation
- changed arm gear ratio
- corrected units in arm from degree to rotation 
- add commands to reset arm motor encoder position
- added operator buttons
=> Many Changes

src/main/java/frc/robot/commands/DriveCommand.java
basecamp card: https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8198367544
=> added code to face cage

src/main/java/frc/robot/subsystems/arm/ArmIOReal.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOReal.java
=> I did the loop thing

src/main/java/frc/robot/subsystems/arm/ArmIOSim.java, src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOReal.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOSim.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8288363104
=> moved to constants

src/main/java/frc/robot/commands/AlignToPose.java
[https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8282370375](url)
=> align to reef changes

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/arm/ArmSubsystem.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8288302305
=>  added comments

src/main/java/frc/robot/commands/DriveCommand.java, src/main/java/frc/robot/subsystems/arm/ArmIOReal.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOReal.java
basecamp task link: https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8282653786
=> Reapply the configs for arm and elevator until they actually apply

src/main/java/frc/robot/RobotContainer.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8288172868
=> prepScoreCoral logs

build.gradle, src/main/java/frc/robot/subsystems/elevator/ElevatorSubsystem.java
1. modify GC settings
2. commented out remote profiling. Can uncomment this when using VisualVM
3. automatically run spotless on build
=> Changes to build.gradle

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AlignToPose.java, src/main/java/frc/robot/commands/DriveCommand.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8307935192
=> Align to pose slew rate limiter

src/main/java/frc/robot/EagleUtil.java, src/main/java/frc/robot/RobotVisualizer.java, src/main/java/frc/robot/commands/autonomous/FiveCycleProcessor.java, src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8282610315
=> Remove unused variables

src/main/java/frc/robot/subsystems/arm/ArmIOReal.java, src/main/java/frc/robot/subsystems/elevator/ElevatorIOReal.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8303164097
=> status signal frequency

src/main/java/frc/robot/RobotContainer.java
Second nearest set points does not change goal while aligning to the second nearest set point, tested in sim
=> second nearest point

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/aprilTagCam/AprilTagCamConstants.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8313847852
=>  added new constants

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/elevator/ElevatorSubsystem.java
changing the PID tuning of the elevator for efficient testing/calibration using the controller commands XYBA, worked with Morgan because he worked on PID tuning of the arm while we did elevator
=> Elevator pid

src/main/java/frc/robot/RobotVisualizer.java, src/main/java/frc/robot/Telemetry.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8328607902
=> i did the reduce smartdashboard call task

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/arm/ArmConstants.java, src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8256529410
=> dealgae command

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/arm/ArmConstants.java, src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java
changed elevator height, arm angle, and gear ratio
=> Angle adjust

src/main/java/frc/robot/subsystems/arm/ArmIOReal.java
https://3.basecamp.com/5677500/buckets/34348388/card_tables/cards/8385950270
=> coast to brake
